#lang racket
(display "\n--------Задание 1--------\n")
(display "Введите время (минут. секунд).\n")
(display "Введите исходные данные:\n")
(display "высота цилиндра (см)\n")
(define t(read))
(define (to_seconds x)
  (* x 60))
(display (format "Секунд: ~a" (to_seconds t)))

(display "\n--------Задание 2--------\n")
(display "Вычисление сопротивления электрической цепи.\n")
(display "Введите исходные данные:\n")
(display "Величина первого сопротивления(Ом) = ")
(define R1(read))
(display "Величина второго сопротивления(Ом) = ")
(define R2(read))
(display "Тип соединения (1 - последовательное, 2 - паралельное) = ")
(define type(read))
(define (parallel x y)
  (/ 1 (+ (/ 1 x) (/ 1 y))))
(define (consistent x y)
  (+ x y))
(define (R x y z)
  (cond ((= z 1) (consistent x y))
        ((= z 2) (parallel x y))))
(display (format "Сопротивление цепи: ~a Ом\n\n" (R R1 R2 type)))

(display "\n--------Задание 3--------\n")
(display "Вычисление площади кольца.\n")
(display "Введите исходные данные:\n")
(display "Радиус кольца(см) = ")
(define ring(read))
(display "Радиус отверстия(см) = ")
(define hole(read))
(define (s x y)
  (- (* 3.14 (* x x)) (* 3.14 (* y y))))
(if (> hole ring)
    (display "Ошибка! Радиус отверстия не может быть больше радиуса кольца.\n\n")
    (display (format "Площадь кольца: ~a см. кв\n\n" (s ring hole))))